apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: edumanage-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edumanage-backend
  template:
    metadata:
      labels:
        app: edumanage-backend
    spec:
      containers:
      - name: edumanage-backend
        image: nginx:1.14.2
        ports:
        - containerPort: 80
