apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: edumanage-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
      nodePort: 31000
  type: NodePort